name: Main
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.ROOT_DATABASE_PASSWORD }}
          MYSQL_USER: ${{ secrets.APP_DATABASE_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.APP_DATABASE_PASSWORD }}
          MYSQL_DATABASE: openrota
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Verify with Maven
        env:
          ROOT_DATABASE_PASSWORD: ${{ secrets.ROOT_DATABASE_PASSWORD }}
          APP_DATABASE_USERNAME: ${{ secrets.APP_DATABASE_USERNAME }}
          APP_DATABASE_PASSWORD: ${{ secrets.APP_DATABASE_PASSWORD }}
        run: mvn verify

      - name: unit test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-coverage
          path: ./target/site/jacoco-unit-test-coverage-report

      - name: integration test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: integration-test-coverage
          path: ./target/site/jacoco-integration-test-coverage-report

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1.2.2
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
