name: Pull request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Verify with Maven
        env:
          ROOT_DATABASE_PASSWORD: ${{ secrets.ROOT_DATABASE_PASSWORD }}
          APP_DATABASE_USERNAME: ${{ secrets.APP_DATABASE_USERNAME }}
          APP_DATABASE_PASSWORD: ${{ secrets.APP_DATABASE_PASSWORD }}
        run: mvn verify
